accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('profile/edit/', views.profile_edit, name='profile_edit'),
  path('password_change/',views.password_change, name='password_change'),
  path('<str:username>/profile/', views.profile_detail, name='profile'),
  path('login/', views.login, name='login'),
  path('logout/', views.logout, name='logout'),
  path('delete/', views.delete, name='delete'),
  path('<str:username>/follower/', views.follow, name='follow'),
]

posts/urls.py
from django.urls import path, re_path, include
from .import views

app_name = 'posts'
urlpatterns = [
  # 영화 디테일 페이지관련
  path('<int:detail_pk>/', views.detail, name='detail'),
  path('<int:detail_pk>/likes/', views.likes, name='likes'),

  # 코멘트 모음 페이지
  path('<int:detail_pk>/comments/', views.comments, name='comments'),

  # 코멘트 페이지 관련
  path('<int:detail_pk>/comments/<int:comment_pk>/', views.comment, name='comment'),
  path('<int:detail_pk>/comment/', views.comment_create, name='comment_create'),
  path('<int:detail_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
  path('<int:detail_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
  path('<int:detail_pk>/comments/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),

  # 코멘트 댓글 관련
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/', views.recomment_create, name='recomment_create'),
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/delete/', views.recomment_delete, name='recomment_delete'),
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/update/', views.recomment_update, name='recomment_update'),
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/likes/', views.recomment_likes, name='recomment_likes'),

  # 검색 페이지 관련
  path('search/', views.search, name='search'),

  # 가짜 어드민 페이지
  re_path(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
]

red_glasses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('socialaccounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class Profile(AbstractUser):
  image = models.ImageField(blank=True, null=True, upload_to='profile/')
  followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)

posts/models.py
from django.db import models
from django.conf import settings
import re
from django.utils import timezone
from datetime import timedelta,datetime
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    # image = models.ImageField(blank=False,upload_to='posters/')
    content = models.TextField()
    poster = models.CharField(max_length=80)
    # score = models.FloatField(null=True)
    # Tag_set = models.ManyToManyField('Tag',blank=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    released_at = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.content)
        tag_list = []
        for tag_name in tag_name_list:
        # get_or_create() 메서드는 두 개의 값을 반환합니다. 첫 번째 값은 검색된 또는 생성된 객체이고, 두 번째 값은 불리언(Boolean) 값으로, 해당 객체가 새로 생성되었는지 여부를 나타냅니다.
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    def count_likes_user(self):
        return self.like_users.count()

    def get_absolute_url(self):
        return reverse('root:index',args=[self.pk])

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.IntegerField()
    movie_title = models.CharField(max_length=20)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    content = models.CharField(max_length=200)
#   rating = models.FloatField(verbose_name='평점')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def count_likes_user(self):
        return self.like_users.count()

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False
        

class Recomment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_recomments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def count_likes_user(self):
        return self.like_users.count()
    
    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False

accounts/forms.py
# from accounts.models import Profile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django import forms


class ProfileForm(UserChangeForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-100 p-2 mb-2',
                'placeholder': '아이디',
            },
        ),
    )
    
    image = forms.ImageField(
        label='이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
            },
        ),
        required=False,
    )
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'image')


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2',)


class CustomPasswordChangeForm(PasswordChangeForm):
        old_password = forms.CharField(
        label='기존 비밀번호',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-100 p-2 mb-2',
                'type': 'password',
            },
        ),
    )
        new_password1 = forms.CharField(
        label='새 비밀번호',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-100 p-2 mb-2',
                'type': 'password',
            },
        ),
    )
        new_password2 = forms.CharField(
        label='새 비밀번호(확인)',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-100 p-2 mb-2',
                'type': 'password',
            },
        ),
    )
        model = get_user_model()
        fields = ('old_password', 'new_password1', 'new_password2',)

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from .forms import CustomUserCreationForm, ProfileForm, CustomPasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.shortcuts import render, redirect
from django.http import JsonResponse


def login(request):
    next = request.GET.get('next')
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect(next)
        else:
            return render(request, 'index.html', {'error': '아이디 또는 비밀번호가 올바르지 않습니다.'})
    else:
        return render(request, 'index.html', {'next': next})


def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('index')


def signup(request):
    next = request.GET.get('next')
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST.get('username')
            password = request.POST.get('password1')
            user = authenticate(request, username=username, password=password)
            auth_login(request, user)
            return redirect(next)
        else:
            return render(request, 'index.html', {'error': '아이디 또는 비밀번호가 올바르지 않습니다.'})
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'index.html', context)


def profile_detail(request, username):
    person = get_user_model().objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


# 프로필 수정
@login_required
def profile_edit(request):
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', username=request.user.username)
    else:
        form = ProfileForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request,'accounts/profile_edit.html', context)


# 비밀번호 수정
@login_required
def password_change(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:profile', request.user.username)
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/password_change.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('index')


@login_required
def follow(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)

    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
            is_followed = False
        else:
            person.followers.add(request.user)
            is_followed = True
        context = {
            'is_followed' : is_followed,
            'followings_count': person.followings.count(),
            'followers_count': person.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', person.username)

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>비밀번호 수정</title>
<link rel="stylesheet" href="{% static 'css/password_change.css' %}">
{% endblock head %}

{% block content %}
<main>
    <div class="container profile-edit_form">
        <div class="d-flex justify-content-center mb-5">
            <h3>비밀번호 수정</h3>
        </div>
        <form action="{% url 'accounts:password_change' %}" method="POST">
            {% csrf_token %}
            <div>
                <p>{{ form.old_password.label }}</p>
                <p>{{ form.old_password }}</p>
            </div>
            <div>
                <p>{{ form.new_password1.label }}</p>
                <p>{{ form.new_password1 }}</p>
            </div>
            <div>
                <p>{{ form.new_password2.label }}</p>
                <p>{{ form.new_password2 }}</p>
            </div>
            <input type="submit" class="profile-submit_btn mt-3" value="비밀번호 수정">
        </form>
    </div>
</main>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>RED-GLASSES</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" />
{% endblock head %}

{% block content %}
{% comment %} <a href="{% url 'accounts:profile_edit' %}">프로필 수정</a> {% endcomment %}
<div class="profile-container mb-5">
  <div class="img-cover">
    <img src="https://wallpaperaccess.com/full/1204591.jpg" alt=""/>
  </div>
  <div class="profile-info">
    <div class="profile-image">
      {% if person.image %}
      <img src="{{ person.image.url }}" alt="">
      {% else %}
      <img src="{% static 'img/no_profile.jpg' %}" alt="">
      {% endif %}
    </div>
    <div class="d-flex align-items-center gap-3">
      <h3 class="mt-2"><b>{{person}}</b></h3>
      {% if request.user != person %}
      <form id="follow-form" data-user-id="{{ person.username }}">
        {% csrf_token %}
        {% if request.user in person.followers.all %}
        <input type="submit" value='언팔로우' class="profile-unfollow_btn">
        {% else %}
        <input type="submit" value='팔로우' class="profile-follow_btn">
        {% endif %}
      </form>
      {% endif %}
    </div>
    <div>
      팔로워 <a type="button" data-bs-toggle="modal" data-bs-target="#followersModal"><b><span id="followers-count">{{ person.followers.all|length }}</span></b></a> · 
      팔로잉 <a type="button" data-bs-toggle="modal" data-bs-target="#followingsModal"><b><span id="followings-count">{{ person.followings.all|length }}</span></b></a>
    </div>
  </div>


  <div class="accordion accordion-flush border-top border-bottom" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          <div class="d-flex gap-2">
            <span><b>보고싶은 영화</b></span>
            <span class="text-secondary">{{ person.like_posts.all|length }}</span>
          </div>
        </button>
      </h2>
      <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">
          {% for post in person.like_posts.all|dictsortreversed:'created_at' %}
          <a href="{% url 'posts:detail' post.id %}">
            <div class="d-flex align-items-center justify-content-between p-2 border-bottom like-post">
              <div class="d-flex align-items-center gap-3">
                <div class="poster-form">
                  <img src="https://image.tmdb.org/t/p/original/{{ post.poster }}" alt="">
                </div>
                <div>{{ post.title }}</div>
              </div>
              <div class="post-release">개봉 : {{ post.released_at }}</div>
            </div>
          </a>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
          <div class="d-flex gap-2">
            <span><b>코멘트</b></span>
            <span class="text-secondary">{{ person.comment_set.all|length }}</span>
          </div>
        </button>
      </h2>
      <div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">
          {% for comment in person.comment_set.all|dictsortreversed:'created_at' %}
          <a href="{% url 'posts:comment' comment.movie comment.id %}">
            <div class="comment-form d-flex justify-content-between gap-4">
              <div class="d-flex flex-column gap-2">
                <div class="movie-title">{{ comment.movie_title }}</div>
                <div>{{ comment.content }}</div>
              </div>
              <div class="d-flex align-items-end comment-created_at">{{ comment.created_string }}</div>
            </div>
          </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-center m-4">
    <div class="d-grid gap-3 d-md-flex justify-content-md-end align-items-center">
      <a href="{% url 'accounts:logout' %}" type="button" class="feature-btn">
        로그아웃
      </a> ·
      <a href="{% url 'accounts:profile_edit' %}" type="button" class="feature-btn">
        회원정보 수정
      </a> ·
      <form action="{% url 'accounts:delete' %}" method="POST">
        {% csrf_token %}
        <input type="submit" class=" bg-transparent border-0 feature-btn" value="회원탈퇴" onclick="return confirm('탈퇴 하시겠습니까?')">
      </form>
    </div>
  </div>
</div>

<!-- 팔로워 Modal -->
<div class="modal fade" id="followersModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">팔로워</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {% for follower in person.followers.all %}
        <a href="{% url 'accounts:profile' follower.username %}">
          <div class="d-flex align-items-center gap-3">
            <div class="follow-profile_form">
              {% if follower.image %}
              <img src="{{ follower.image.url }}" alt="">
              {% else %}
              <img src="{% static 'img/no_profile.jpg' %}" alt="">
              {% endif %}
            </div>
            <div>{{ follower.username }}</div>
          </div>
        </a>
        <hr>
        {% endfor %}
      </div>
    </div>
  </div>
</div>


<!-- 팔로잉 Modal -->
<div class="modal fade" id="followingsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">팔로잉</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {% for following in person.followings.all %}
        <a href="{% url 'accounts:profile' following.username %}">
          <div class="d-flex align-items-center gap-3">
            <div class="follow-profile_form">
              {% if follower.image %}
              <img src="{{ following.image.url }}" alt="">
              {% else %}
              <img src="{% static 'img/no_profile.jpg' %}" alt="">
              {% endif %}
            </div>
            <div>{{ following.username }}</div>
          </div>
        </a>
        <hr>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/follow.js' %}"></script>
{% endblock script %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>회원정보수정</title>
<link rel="stylesheet" href="{% static 'css/profile_edit.css' %}">
{% endblock head %}

{% block content %}
<main>
    <div class="container profile-edit_form">
        <div class="mb-5">
            <h3>회원정보 수정</h3>
        </div>
        <form action="{% url 'accounts:profile_edit' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <p>{{ form.username.label }}</p>
                <p>{{ form.username }}</p>
            </div>
            <div>
                <p>{{ form.image.label }}</p>
                <p>{{ form.image }}</p>
            </div>
            <input type="submit" class="profile-submit_btn mt-3" value="프로필 수정">
        </form>
    </div>
</main>
{% endblock content %}