accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('profile/edit/', views.profile_edit, name='profile_edit'),
  path('password_change/',views.password_change, name='password_change'),
  path('<str:username>/profile/', views.profile_detail, name='profile'),
  path('login/', views.login, name='login'),
  path('logout/', views.logout, name='logout'),
  path('delete/', views.delete, name='delete'),
  path('<str:username>/follower/', views.follow, name='follow'),
]

posts/urls.py
from django.urls import path, re_path, include
from .import views

app_name = 'posts'
urlpatterns = [
  # 영화 디테일 페이지관련
  path('<int:detail_pk>/', views.detail, name='detail'),
  path('<int:detail_pk>/likes/', views.likes, name='likes'),

  # 코멘트 모음 페이지
  path('<int:detail_pk>/comments/', views.comments, name='comments'),

  # 코멘트 페이지 관련
  path('<int:detail_pk>/comments/<int:comment_pk>/', views.comment, name='comment'),
  path('<int:detail_pk>/comment/', views.comment_create, name='comment_create'),
  path('<int:detail_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
  path('<int:detail_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
  path('<int:detail_pk>/comments/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),

  # 코멘트 댓글 관련
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/', views.recomment_create, name='recomment_create'),
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/delete/', views.recomment_delete, name='recomment_delete'),
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/update/', views.recomment_update, name='recomment_update'),
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/likes/', views.recomment_likes, name='recomment_likes'),

  # 검색 페이지 관련
  path('search/', views.search, name='search'),

  # 가짜 어드민 페이지
  re_path(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
]

red_glasses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('socialaccounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Watcha Pedia</title>
    <link rel="short icon" href="{% static 'img/favicon.jpeg' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock head %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg fixed-top" id="nav">
            <div class="container">
                <!-- 로고 -->
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.svg' %}" alt="logo" class="base-logo" id="nav-Logo">
                </a>

                <div class="d-flex align-items-center gap-3">
                    <!-- 검색 -->
                    <form action="{% url 'posts:search' %}" method="GET" class="d-flex" role="search">
                        <label for="search" class="d-flex align-items-center search-label bg-light" id="search-label">
                            <span class="material-symbols-outlined text-body-tertiary" id='search-icon'>
                                search
                            </span>
                            <input class="search-input border-0 bg-light ms-1" type="search" placeholder="콘텐츠, 인물, 컬렉션, 유저를 검색해보세요." name="q" aria-label="Search" id="search" value="{{ query }}">
                        </label>
                    </form>
                    
                    {% if request.user.is_authenticated %}
                    <div class="dropdown">
                        <a data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="profile-form">
                                {% if request.user.image %}
                                <img src="{{ request.user.image.url }}" alt="">
                                {% else %}
                                <img src="{% static 'img/no_profile.jpg' %}" alt="">
                                {% endif %}
                            </div>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:profile' user.username %}">
                                    <span class="material-symbols-outlined">person</span>
                                    <p class='font-12 my-auto ms-2'>프로필</p>
                                </a>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:profile_edit' %}">
                                    <span class="material-symbols-outlined">manage_accounts</span>
                                    <p class='font-12 my-auto ms-2'>회원정보 수정</p>
                                </a>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <form action="{% url 'accounts:logout' %}" method='POST' class='dropdown-item font-12 p-0 ps-3'>
                                    {% csrf_token %}
                                    <div class='d-flex align-items-center'>
                                        <span class="material-symbols-outlined">logout</span>
                                        <input type="submit" value='로그아웃' class='dropdown-item p-0 ms-2'>
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </div>
                    {% else %}
                    <!-- 로그인 및 회원가입 -->
                    <a type="button" data-bs-toggle="modal" data-bs-target="#loginModal" class="text-decoration-none text-secondary login-Btn">로그인</a>
                    <a href="{% url 'accounts:signup' %}" type="button" data-bs-toggle="modal" data-bs-target="#signupModal" class="text-decoration-none text-secondary signup-Btn">회원가입</a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>

    {% block content %}{% endblock content %}

    <footer>
        <section class="d-flex justify-content-center align-items-center bg-black fw-normal fs-5 gap-2">
            <span class="text-white">지금까지</span>
            <span class="survey-cnt"> ★ 0000000 개의 평가가 </span>
            <span class="text-white">쌓였어요.</span>
        </section>
        <section>
            <div class="container">
                <div class="d-flex align-items-center">
                    <div class="col-6 d-flex flex-column gap-1 mt-5">
                        <img src="{% static 'img/logo_gray.png' %}" alt="logo" class="base-logo">
                        <div>Copyright &copy; 2023 team 1. <a href="https://github.com/red-glasses1/Red_glassess" class="text-light text-decoration-none">빨간 안경</a>
                        </div>
                        <div>multi-campus KDT 2th semi-project2</div>
                    </div>
                    <div class="col-6 d-flex gap-3 mt-5 justify-content-end">
                        <div class="me-4"><b>Members</b></div>
                        <div class="d-flex flex-column gap-3">
                            <a class="text-decoration-none text-secondary" href="https://github.com/S05p">김강섭</a>
                            <a class="text-decoration-none text-secondary" href="https://github.com/kimchowon98">김초원</a>
                        </div>
                        <div class="d-flex flex-column gap-3">
                            <a class="text-decoration-none text-secondary" href="https://github.com/mangji12">오창인</a>
                            <a class="text-decoration-none text-secondary" href="https://github.com/IM-jihye">임지혜</a>
                        </div>
                        <div class="d-flex flex-column gap-3">
                            <a class="text-decoration-none text-secondary" href="https://github.com/JeonggonCho">조정곤</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </footer>

    <!-- login Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content flex-column align-items-center w-75 p-4 py-5">
                <!-- 로그인 타이틀 -->
                <div class="d-flex flex-column align-items-center gap-5 mb-3">
                    <img src="{% static 'img/logo.svg' %}" alt="">
                    <h6><b>로그인</b></h6>
                </div>
                
                <!-- 로그인 입력부분 -->
                <form action="{% url 'accounts:login' %}?next={{ request.path }}" method="POST" class="d-flex flex-column w-100 gap-2 mb-4">
                    {% csrf_token %}
                    <input type="text" name='username' placeholder="아이디" class="w-100 email-input">
                    <input type="password" name='password' placeholder="비밀번호" class="w-100 password-input">
                    <input type="submit" value="로그인" class="log-submit_btn mt-3 w-100">
                </form>
                
                <!-- 회원가입 연결 -->
                <div class="log-link">
                    <span>계정이 없으신가요?</span>
                    <a href="#" data-bs-toggle="modal" data-bs-target="#signupModal">회원가입</a>
                </div>
                <div class="d-flex align-items-center gap-3 w-100 mt-3">
                    <div class="line"></div>
                    <div class="text-secondary">OR</div>
                    <div class="line"></div>
                </div>
                <!-- 소셜로그인 연결 -->
                <div class="d-flex align-items-center justify-content-center gap-3 w-100 mt-3">
                    <a href="{% provider_login_url 'kakao'%}" class="kakao-log_btn d-flex align-items-center justify-content-center"><img src="{% static 'img/kakao_logo.png' %}" alt="" style="width: 22px; height: 20px;"></a>
                    <a href="{% provider_login_url 'google'%}" class="google-log_btn d-flex align-items-center justify-content-center"><img src="{% static 'img/Google_logo.png' %}" alt="" style="width: 20px; height: 20px;"></a>
                    <a href="{% provider_login_url 'naver'%}"class="naver-log_btn d-flex align-items-center justify-content-center text-white fw-bold fs-4 text-decoration-none">N</a>
                </div>
            </div>
        </div>
    </div>

    <!-- signup Modal -->
    <div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content flex-column align-items-center w-75 p-4 py-5">
                <!-- 회원가입 타이틀 -->
                <div class="d-flex flex-column align-items-center gap-5 mb-3">
                    <img src="{% static 'img/logo.svg' %}" alt="">
                    <h6><b>회원가입</b></h6>
                </div>

                <!-- 회원가입 입력부분 -->
                <form action="{% url 'accounts:signup' %}?next={{ request.path }}" method="POST" class="d-flex flex-column log-input w-100 gap-2 mb-4">
                    {% csrf_token %}
                    <input type="text" name='username' placeholder="아이디" class="id-input">
                    <input type="email" name='email' placeholder="이메일" class="email-input">
                    <input type="password" name='password1' placeholder="비밀번호" class="password-input">
                    <input type="password" name='password2' placeholder="비밀번호 확인" class="password-input">
                    <input type="submit" value="회원가입" class="log-submit_btn mt-3">
                </form>

                <!-- 로그인 연결 -->
                <div class="log-link">
                    <span>이미 가입하셨나요?</span>
                    <a href="#" data-bs-toggle="modal" data-bs-target="#loginModal">로그인</a>
                </div>
                <div class="d-flex align-items-center gap-3 w-100 mt-3">
                    <div class="line"></div>
                    <div class="text-secondary">OR</div>
                    <div class="line"></div>
                </div>
                <!-- 소셜로그인 연결 -->
                <div class="d-flex align-items-center justify-content-center gap-3 w-100 mt-3">
                    <a href="{% provider_login_url 'kakao'%}" class="kakao-log_btn d-flex align-items-center justify-content-center"><img src="{% static 'img/kakao_logo.png' %}" alt="" style="width: 22px; height: 20px;"></a>
                    <a href="{% provider_login_url 'google'%}" class="google-log_btn d-flex align-items-center justify-content-center"><img src="{% static 'img/Google_logo.png' %}" alt="" style="width: 20px; height: 20px;"></a>
                    <a href="{% provider_login_url 'naver'%}"class="naver-log_btn d-flex align-items-center justify-content-center text-white fw-bold fs-4 text-decoration-none">N</a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    {% block script %}{% endblock script %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock head %}

{% block content %}
<main>
    <div class="container mb-5">
        <section class="index-category">
        {% if error %}
            <div class="d-flex justify-content-center fs-5">{{ error }}</div>
        {% else %}
            <div class="index-category_title">
                <b>인기영화 순위</b>
            </div>

            <div id="popularCarousel" class="carousel carousel-dark slide">
                <div class="carousel-inner">
                    {% for popular in popular_movies %}
                        {% if forloop.counter0|divisibleby:5 %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <div class="row">
                                <ul class="card-wrapper">
                        {% endif %}
                                <li class="card">
                                    <a href="{% url 'posts:detail' popular.id %}">
                                        <div class="image-wrapper">
                                            <div class="rank-marker">{{ popular.rank }}</div>
                                            <img src="https://image.tmdb.org/t/p/w500/{{ popular.poster_path }}" alt="...">
                                        </div>
                                        <div class="card-body">
                                            <div class="card-text">{{ popular.title }}</div>
                                            <div>
                                                <span>개봉 : {{ popular.release_date }}</span>
                                                <div class='color-pink'>예상평점★{{ popular.vote_average }}</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                        {% if forloop.counter|divisibleby:5 or forloop.last %}
                                </ul>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <button id="prevBtn" class="carousel-control-prev" type="button" data-bs-target="#popularCarousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </button>
                <button id="nextBtn" class="carousel-control-next" type="button" data-bs-target="#popularCarousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </button>
            </div>
        </section>


        <section class="index-category">
            <div class="index-category_title">
                <b>현재 상영중인 영화</b>
            </div>

            <div id="nowPlayingCarousel" class="carousel carousel-dark slide">
                <div class="carousel-inner">
                    {% for now_playing in now_playing_movies %}
                        {% if forloop.counter0|divisibleby:5 %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <div class="row">
                                <ul class="card-wrapper">
                        {% endif %}
                                <li class="card">
                                    <a href="{% url 'posts:detail' now_playing.id %}">
                                        <div class="image-wrapper">
                                            <div class="rank-marker">{{ now_playing.rank }}</div>
                                            <img src="https://image.tmdb.org/t/p/w500/{{ now_playing.poster_path }}" alt="...">
                                        </div>
                                        <div class="card-body">
                                            <div class="card-text">{{ now_playing.title }}</div>
                                            <div>
                                                <span>개봉 : {{ now_playing.release_date }}</span>
                                                <div class='color-pink'>예상평점★{{ now_playing.vote_average }}</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                        {% if forloop.counter|divisibleby:5 or forloop.last %}
                                </ul>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <button id="prevBtn" class="carousel-control-prev" type="button" data-bs-target="#nowPlayingCarousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </button>
                <button id="nextBtn" class="carousel-control-next" type="button" data-bs-target="#nowPlayingCarousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </button>
            </div>
        </section>


        <section class="index-category">
            <div class="index-category_title">
                <b>개봉예정 영화</b>
            </div>

            <div id="upcomingCarousel" class="carousel carousel-dark slide">
                <div class="carousel-inner">
                    {% for upcoming in upcoming_movies %}
                        {% if forloop.counter0|divisibleby:5 %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <div class="row">
                                <ul class="card-wrapper">
                        {% endif %}
                                <li class="card">
                                    <a href="{% url 'posts:detail' upcoming.id %}">
                                        <div class="image-wrapper">
                                            <img src="https://image.tmdb.org/t/p/w500/{{ upcoming.poster_path }}" alt="...">
                                        </div>
                                        <div class="card-body">
                                            <div class="card-text">{{ upcoming.title }}</div>
                                            <div>
                                                <span>개봉 예정 : <span class='color-pink'>{{ upcoming.release_date }}</span></span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                        {% if forloop.counter|divisibleby:5 or forloop.last %}
                                </ul>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <button id="prevBtn" class="carousel-control-prev" type="button" data-bs-target="#upcomingCarousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </button>
                <button id="nextBtn" class="carousel-control-next" type="button" data-bs-target="#upcomingCarousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </button>
            </div>
        </section>
        {% endif %}
    </div>
</main>
{% endblock content %}

{% block script %}{% endblock script %}