accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('profile/edit/', views.profile_edit, name='profile_edit'),
  path('password_change/',views.password_change, name='password_change'),
  path('<str:username>/profile/', views.profile_detail, name='profile'),
  path('login/', views.login, name='login'),
  path('logout/', views.logout, name='logout'),
  path('delete/', views.delete, name='delete'),
  path('<str:username>/follower/', views.follow, name='follow'),
]

posts/urls.py
from django.urls import path, re_path, include
from .import views

app_name = 'posts'
urlpatterns = [
  # 영화 디테일 페이지관련
  path('<int:detail_pk>/', views.detail, name='detail'),
  path('<int:detail_pk>/likes/', views.likes, name='likes'),

  # 코멘트 모음 페이지
  path('<int:detail_pk>/comments/', views.comments, name='comments'),

  # 코멘트 페이지 관련
  path('<int:detail_pk>/comments/<int:comment_pk>/', views.comment, name='comment'),
  path('<int:detail_pk>/comment/', views.comment_create, name='comment_create'),
  path('<int:detail_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
  path('<int:detail_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
  path('<int:detail_pk>/comments/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),

  # 코멘트 댓글 관련
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/', views.recomment_create, name='recomment_create'),
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/delete/', views.recomment_delete, name='recomment_delete'),
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/update/', views.recomment_update, name='recomment_update'),
  path('<int:detail_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/likes/', views.recomment_likes, name='recomment_likes'),

  # 검색 페이지 관련
  path('search/', views.search, name='search'),

  # 가짜 어드민 페이지
  re_path(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
]

red_glasses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('socialaccounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.conf import settings
import re
from django.utils import timezone
from datetime import timedelta,datetime
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    # image = models.ImageField(blank=False,upload_to='posters/')
    content = models.TextField()
    poster = models.CharField(max_length=80)
    # score = models.FloatField(null=True)
    # Tag_set = models.ManyToManyField('Tag',blank=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    released_at = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.content)
        tag_list = []
        for tag_name in tag_name_list:
        # get_or_create() 메서드는 두 개의 값을 반환합니다. 첫 번째 값은 검색된 또는 생성된 객체이고, 두 번째 값은 불리언(Boolean) 값으로, 해당 객체가 새로 생성되었는지 여부를 나타냅니다.
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    def count_likes_user(self):
        return self.like_users.count()

    def get_absolute_url(self):
        return reverse('root:index',args=[self.pk])

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.IntegerField()
    movie_title = models.CharField(max_length=20)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    content = models.CharField(max_length=200)
#   rating = models.FloatField(verbose_name='평점')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def count_likes_user(self):
        return self.like_users.count()

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False
        

class Recomment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_recomments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def count_likes_user(self):
        return self.like_users.count()
    
    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False

posts/forms.py
from django import forms
from .models import Comment, Recomment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


class RecommentForm(forms.ModelForm):
    class Meta:
        model = Recomment
        fields = ('content',)

posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import JsonResponse
from posts.models import Post, Comment, Recomment
from .forms import CommentForm, RecommentForm
import requests, os
from dotenv import load_dotenv

load_dotenv()


# 디테일 페이지
def detail(request, detail_pk):
    # 영화 디테일 정보받기
    detail_url = f"https://api.themoviedb.org/3/movie/{detail_pk}"

    params = {
        "api_key": "ad54a63bd524b655ee79f3f3108ba520",  # os.getenv('TMDB_API'),
        "language": "ko-KR",
    }

    detail_response = requests.get(detail_url, params=params)
    detail = detail_response.json()
    genres = detail_response.json()["genres"]
    score = round(detail_response.json()["vote_average"], 2)

    # 영화 이미지 받기
    gallery_url = f"https://api.themoviedb.org/3/movie/{detail_pk}/images"

    params = {
        "api_key": "ad54a63bd524b655ee79f3f3108ba520",  # os.getenv("TMDB_API"),
    }

    gallery_response = requests.get(gallery_url, params=params)
    gallery = gallery_response.json()["backdrops"]

    # 영화 출연진 정보받기
    credits_url = f"https://api.themoviedb.org/3/movie/{detail_pk}/credits"

    credits_response = requests.get(credits_url, params=params)
    credits = credits_response.json()["cast"][:10]

    if (
        detail_response.status_code == 200
        and gallery_response.status_code == 200
        and credits_response.status_code == 200
    ):
        movie_data = detail
        id = movie_data["id"]
        title = movie_data["title"]
        content = movie_data["overview"]
        release_date = movie_data["release_date"]
        poster = movie_data["poster_path"]
        posts = Post.objects.all()
        movie = Post(
            id=id, title=title, content=content, poster=poster, released_at=release_date
        )
        if movie not in posts:
            movie.save()
    else:
        raise Exception("영화 정보를 가져오는데 실패했습니다.")
    comments = Comment.objects.filter(movie=detail_pk).order_by("-created_at")[:9]

    context = {
        "movie": movie,
        "detail": detail,
        "genres": genres,
        "gallery": gallery,
        "score": score,
        "credits": credits,
        "comments": comments,
    }
    return render(request, "posts/detail.html", context)


# 영화 보고싶어요 기능
@login_required
def likes(request, detail_pk):
    post = Post.objects.get(pk=detail_pk)

    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
        is_liked = False
    else:
        post.like_users.add(request.user)
        is_liked = True
    context = {
        "is_liked": is_liked,
    }
    return JsonResponse(context)


# 코멘트 모음 페이지
def comments(request, detail_pk):
    comments = Comment.objects.filter(movie=detail_pk).order_by("-created_at")
    context = {
        "comments": comments,
        "detail_pk": detail_pk,
    }
    return render(request, "posts/comments.html", context)


# 단일 코멘트 페이지
def comment(request, detail_pk, comment_pk):
    comment = Comment.objects.get(movie=detail_pk, pk=comment_pk)
    recomments = comment.recomment_set.all().order_by("-created_at")

    # 영화 디테일 정보받기
    detail_url = f"https://api.themoviedb.org/3/movie/{detail_pk}"

    params = {
        "api_key": "ad54a63bd524b655ee79f3f3108ba520",  # os.getenv("TMDB_API"),
        "language": "ko-KR",
    }

    detail_response = requests.get(detail_url, params=params)
    detail = detail_response.json()

    context = {
        "comment": comment,
        "detail": detail,
        "recomments": recomments,
    }
    return render(request, "posts/comment.html", context)


# 코멘트 생성
@login_required
def comment_create(request, detail_pk):
    movie_title = request.GET.get("movie_title")
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.movie = detail_pk
            comment.movie_title = movie_title
            comment.user = request.user
            comment.save()
            return redirect("posts:detail", detail_pk)
    else:
        form = CommentForm()
    context = {
        "form": form,
    }
    return render(request, "posts/detail.html", context)


# 코멘트 수정
@login_required
def comment_update(request, detail_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        if request.method == "POST":
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.movie = detail_pk
                comment.user = request.user
                comment.save()
                return redirect("posts:comment", detail_pk, comment_pk)
    return redirect("posts:comment", detail_pk, comment_pk)


# 코멘트 삭제
@login_required
def comment_delete(request, detail_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect("posts:detail", detail_pk)


# 코멘트 좋아요
@login_required
def comment_likes(request, detail_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)

    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
        is_liked = False
    else:
        comment.like_users.add(request.user)
        is_liked = True
    context = {
        "is_liked": is_liked,
        "like_count": comment.like_users.count(),
    }
    return JsonResponse(context)


# 코멘트 댓글 생성
@login_required
def recomment_create(request, detail_pk, comment_pk):
    if request.method == "POST":
        form = RecommentForm(request.POST)
        if form.is_valid():
            recomment = form.save(commit=False)
            recomment.comment_id = comment_pk
            recomment.user = request.user
            recomment.save()
            return redirect("posts:comment", detail_pk, comment_pk)
    else:
        form = RecommentForm()
    context = {
        "form": form,
    }
    return render(request, "posts/comment.html", context)


# 코멘트 댓글 삭제
@login_required
def recomment_delete(request, detail_pk, comment_pk, recomment_pk):
    recomment = Recomment.objects.get(pk=recomment_pk)
    if recomment.user == request.user:
        recomment.delete()
    return redirect("posts:comment", detail_pk, comment_pk)


# 코멘트 댓글 수정
@login_required
def recomment_update(request):
    return


# 코멘트 댓글 좋아요
@login_required
def recomment_likes(request, detail_pk, comment_pk, recomment_pk):
    recomment = Recomment.objects.get(pk=recomment_pk)

    if request.user in recomment.like_users.all():
        recomment.like_users.remove(request.user)
        is_liked = False
    else:
        recomment.like_users.add(request.user)
        is_liked = True
    context = {
        "is_liked": is_liked,
        "like_count": recomment.like_users.count(),
    }
    return JsonResponse(context)


# 검색기능 및 페이지
def search(request):
    if "q" in request.GET:
        query = request.GET.get("q")

        # 영화검색
        search_movies_url = "https://api.themoviedb.org/3/search/movie"

        params = {
            "api_key": "ad54a63bd524b655ee79f3f3108ba520",  # os.getenv("TMDB_API"),
            "language": "ko-KR",
            "query": query,
            "page": "1",
            "region": "KR",
        }

        search_movies_response = requests.get(search_movies_url, params=params)
        search_movies_info = search_movies_response.json()
        search_movies = search_movies_info["results"]

        # 인물검색
        search_person_url = "https://api.themoviedb.org/3/search/person"

        search_person_response = requests.get(search_person_url, params=params)
        search_person_info = search_person_response.json()
        search_person = search_person_info["results"]

    context = {
        "query": query,
        "search_movies": search_movies,
        "search_person": search_person,
    }

    return render(request, "posts/search.html", context)

posts/templates/posts/comments.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>코멘트 목록</title>
<link rel="stylesheet" href="{% static 'css/comments.css' %}">
{% endblock head %}

{% block content %}
<main>
    <div class="border-bottom bg-white mt-5 p-3 pb-2 comments-nav" id="comments-nav">
        <a href="{% url 'posts:detail' detail_pk %}">
            <span class="material-symbols-outlined color-pink">keyboard_backspace</span>
        </a>
        <h5 id="comments-title"><b>코멘트</b></h5>
    </div>
    <div class="container">
        {% for comment in comments %}
        <li class="comment-card">
            <div class="d-flex justify-content-between align-items-center border-bottom mb-3">
                <a href="{% url 'accounts:profile' comment.user.username %}" class="d-flex align-items-center gap-2 py-2">
                    <div class="profile-image-form">
                        {% if comment.user.image %}
                        <img src="{{ comment.user.image.url }}" alt="">
                        {% else %}
                        <img src="{% static 'img/no_profile.jpg' %}" alt="">
                        {% endif %}
                    </div>
                    <div><b>{{ comment.user }}</b></div>
                </a>
                <div class="comment-score font-14">★4.5</div>
            </div>
            <a href="{% url 'posts:comment' comment.movie comment.id %}">
                <div class="comment-content border-bottom">{{ comment.content }}</div>
            </a>
            <div class="d-flex align-items-center gap-3 border-bottom mb-2">
                <div class="d-flex align-items-center gap-2 py-2">
                    <span class="material-symbols-outlined text-secondary font-15">thumb_up</span>
                    <div class="font-14" id="like-count-{{ detail_pk }}-{{ comment.id }}">{{ comment.count_likes_user }}</div>
                </div>
                <div class="d-flex align-items-center gap-2">
                    <span class="material-symbols-outlined text-secondary font-15">chat_bubble</span>
                    <div class="font-14">{{ comment.recomment_set.all|length }}</div>
                </div>
            </div>
            <form class="comment-like-forms" data-detail-id="{{ detail_pk}}" data-comment-id="{{ comment.id }}">
                {% csrf_token %}
                {% if request.user in comment.like_users.all %}
                <input type="submit" id="like-{{ detail_pk }}-{{ comment.id }}" class="comment-unlike_btn" value="좋아요">
                {% else %}
                <input type="submit" id="like-{{ detail_pk }}-{{ comment.id }}" class="comment-like_btn" value="좋아요">
                {% endif %}
            </form>
        </li>
        {% endfor %}
    </div>
</main>
{% endblock content %}

{% block script %}
<script src="{% static 'js/commentsTitle.js' %}"></script>
<script src="{% static 'js/commentsLikes.js' %}"></script>
{% endblock script %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<title>영화정보</title>
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock head %}

{% block content %}
<main>
    <!-- 영화 기본 정보 -->
    <section class="detail-movie_info border-bottom">
        <!-- 영화 이미지 배너 -->
        <div class="detail-banner_wrapper">
        <div class="filter"></div>
        {% for image in gallery %}
        <img src="https://image.tmdb.org/t/p/original/{{ image.file_path }}"/>
        {% endfor %}
        </div>

        <div class="d-flex gap-4 basic-info">
            <div class="detail-poster_wrapper">
                <img src="https://image.tmdb.org/t/p/w500/{{ detail.poster_path }}" alt=""/>
            </div>
            <div class="d-flex flex-column">
                <h1 class="mt-5"><b>{{ detail.title }}</b></h1>
                <span class="mb-2 text-secondary font-15">{{ detail.release_date }}・
                    {% for genre in genres %}
                    {{ genre.name }},
                    {% endfor %}
                <div class="mb-3 py-2 d-flex border-top border-bottom font-15">
                    <span class="color-pink">예상평점 ★{{ score }}</span>
                </div>
                <div class="d-flex gap-4">
                <div class="d-flex flex-column align-items-center">
                    <span class="text-secondary font-12">평가하기</span>
                    <span class="rating_box">
                        <div class="rating">
                        ★★★★★
                        <span class="rating_star">★★★★★</span>
                        <input type="range" value="1" step="1" min="0" max="10">
                        </div>
                    </span>
                </div>
                <div class="vertical-line"></div>
                <form class="detail-like-forms d-flex align-items-center" data-detail-id="{{ detail.id }}">
                    {% csrf_token %}
                    {% if request.user in movie.like_users.all %}
                    <button type="submit" class="d-flex align-items-center gap-2 feature-btn border-0 bg-transparent detail-unlike_btn" id="like-{{ detail.id }}">
                        <span class="material-symbols-outlined">add</span>
                        <span>보고싶어요</span>
                    </button>
                    {% else %}
                    <button type="submit" class="d-flex align-items-center gap-2 feature-btn border-0 bg-transparent detail-like_btn" id="like-{{ detail.id }}">
                        <span class="material-symbols-outlined">add</span>
                        <span>보고싶어요</span>
                    </button>
                    {% endif %}
                </form>
                <a type="button" data-bs-toggle="modal" data-bs-target="#commentModal" class="d-flex align-items-center gap-2 feature-btn">
                    <span class="material-symbols-outlined">edit</span>
                    <span class="font-14">코멘트</span>
                </a>
                {% comment %} <a href="#" class="d-flex align-items-center gap-2 feature-btn">
                    <span class="material-symbols-outlined">visibility</span>
                    <span class="font-14">보는중</span>
                </a>
                <a href="#" class="d-flex align-items-center gap-2 feature-btn">
                    <span class="material-symbols-outlined">more_horiz</span>
                    <span class="font-14">더보기</span>
                </a> {% endcomment %}
                </div>
            </div>
        </div>
    </section>

    <!-- 영화 상세 정보 -->
    <section class="py-4">
        <div class="detail-info">
            <div class="border bg-white p-4">
                <!-- 내가 좋아할 이유 -->
                {% comment %} <div class="d-flex flex-column gap-3 mb-4">
                    <h2><b>내가 좋아할 이유</b></h2>
                    <div class="d-flex justify-content-between border-bottom pb-2">
                        <div class="text-secondary font-15">선호하는 배우</div>
                        <div class="font-15">조 샐다나</div>
                    </div>
                    <div class="d-flex justify-content-between border-bottom pb-2">
                        <div class="text-secondary font-15">재밌게 본 비슷한 작품</div>
                        <div class="font-15">블랙팬서: 와칸다 포에버</div>
                    </div>
                    <div class="d-flex justify-content-between border-bottom pb-2">
                        <div class="text-secondary font-15">선호하는 태그</div>
                        <div class="font-15">#마블 #우주선</div>
                    </div>
                </div> {% endcomment %}

                <!-- 기본 정보 -->
                <div class="mb-4 pb-3 border-bottom">
                    <div class="d-flex justify-content-between mb-2">
                        <h2><b>기본 정보</b></h2>
                    </div>
                    <div class="text-secondary font-15">{{ detail.original_title }}</div>
                    <div class="text-secondary font-15">{{ detail.release_date }} · 
                        {% for genre in genres %}
                        {{ genre.name }},
                        {% endfor %}
                    </div>
                    <div class="text-secondary font-15">{{ detail.runtime }}분</div>
                    <div class="text-secondary font-15">{{ detail.overview }}</div>
                </div>

                <!-- 출연진 -->
                <div class="mb-4 pb-3">
                    <div class="d-flex justify-content-between mb-2">
                        <h2><b>출연</b></h2>
                    </div>
                    <div class="row w-100">
                        {% for credit in credits %}
                        <div class="col-6 d-flex align-items-center gap-2 pb-2 mb-2">
                            <div class="credit-image_form">
                                {% if credit.profile_path %}
                                <img src="https://image.tmdb.org/t/p/w500/{{ credit.profile_path }}" alt="">
                                {% else %}
                                <img src="{% static 'img/no_profile.jpg' %}" alt="">
                                {% endif %}
                            </div>
                            <div class="credit-info border-bottom">
                                <div class="font-17">{{ credit.name }}</div>
                                <div class="text-secondary font-14">{{ credit.character }}</div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>


                <!-- 별점 그래프 -->
                {% comment %} <div class="mb-4 pb-3 border-bottom">
                    <div class="d-flex justify-content-between mb-3">
                        <h2><b>별점 그래프</b></h2>
                        <div>평균 ★{{ score }}</div>
                    </div>
                    <div>그래프</div>
                </div> {% endcomment %}

                <!-- 코멘트 -->
                <div>
                    <div class="d-flex justify-content-between mb-3">
                        <h2 class="d-flex gap-2"><b>코멘트</b><span class="text-secondary">{{ comments|length }}</span></h2>
                        {% if comments %}
                        <a href="{% url 'posts:comments' detail.id %}" class="color-pink">더보기</a>
                        {% endif %}
                    </div>

                    <!-- 코멘트 carousel -->
                    {% if comments %}
                    <div id="carouselExample" class="carousel carousel-dark slide">
                        <div class="carousel-inner">
                            {% for comment in comments %}
                                {% if forloop.counter0|divisibleby:3 %}
                                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                    <div class="row">
                                        <ul class="card-wrapper gap-3">
                                {% endif %}
                                        <li class="comment-card">
                                            <div class="d-flex justify-content-between align-items-center border-bottom mb-3">
                                                <a href="{% url 'accounts:profile' comment.user.username %}" class="d-flex align-items-center gap-2 py-2">
                                                    <div class="profile-image-form">
                                                        {% if comment.user.image %}
                                                        <img src="{{ comment.user.image.url }}" alt="">
                                                        {% else %}
                                                        <img src="{% static 'img/no_profile.jpg' %}" alt="">
                                                        {% endif %}
                                                    </div>
                                                    <div><b>{{ comment.user }}</b></div>
                                                </a>
                                                <div class="comment-score font-14">★4.5</div>
                                            </div>
                                            <a href="{% url 'posts:comment' comment.movie comment.id %}">
                                                <div class="comment-content border-bottom">{{ comment.content }}</div>
                                            </a>
                                            <div class="d-flex align-items-center gap-3 border-bottom mb-2">
                                                <div class="d-flex align-items-center gap-2 py-2">
                                                    <span class="material-symbols-outlined text-secondary font-15">thumb_up</span>
                                                    <div class="font-14" id="like-count-{{ detail.id }}-{{ comment.id }}">{{ comment.count_likes_user }}</div>
                                                </div>
                                                <div class="d-flex align-items-center gap-2">
                                                    <span class="material-symbols-outlined text-secondary font-15">chat_bubble</span>
                                                    <div class="font-14">{{ comment.recomment_set.all|length }}</div>
                                                </div>
                                            </div>
                                            <form class="comment-like-forms" data-detail-id="{{ detail.id }}" data-comment-id="{{ comment.id }}">
                                                {% csrf_token %}
                                                {% if request.user in comment.like_users.all %}
                                                <input type="submit" id="like-{{ detail.id }}-{{ comment.id }}" class="comment-unlike_btn" value="좋아요">
                                                {% else %}
                                                <input type="submit" id="like-{{ detail.id }}-{{ comment.id }}" class="comment-like_btn" value="좋아요">
                                                {% endif %}
                                            </form>
                                        </li>
                                    {% if forloop.counter|divisibleby:3 or forloop.last %}
                                        </ul>
                                    </div>
                                </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <button id="prevBtn" class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        </button>
                        <button id="nextBtn" class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        </button>
                    </div>
                    {% else %}
                    <div class="d-flex justify-content-center font-gray">코멘트가 없어요.</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
</main>


<!-- 코멘트 작성 Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content w-100 p-3">
            <!-- 코멘트 타이틀 -->
            <div class="d-flex align-items-center justify-content-between mb-3">
                <h6 class="m-0"><b>{{ detail.title }}</b></h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <!-- 코멘트 입력부분 -->
            <form action="{% url 'posts:comment_create' detail.id %}?movie_title={{ detail.title }}" method="POST" class="d-flex flex-column log-input w-100 gap-2">
                {% csrf_token %}
                <textarea name="content" id="content" type="text" cols="30" rows="10" class="border-0 chat-input" placeholder="이 영화에 대한 생각을 자유롭게 표현해주세요."></textarea>
                <div class="d-flex flex-column align-items-end">
                    <input type="submit" value="저장" class="chat-btn border-0 mt-3">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/detailLikes.js' %}"></script>
<script src="{% static 'js/detailRating.js' %}"></script>
<script src="{% static 'js/detailNavbar.js' %}"></script>
<script src="{% static 'js/detail-commentLikes.js' %}"></script>
{% endblock script %}